[package]
name = "tetra-entities"
version.workspace = true
edition.workspace = true

[dependencies]
tetra-core = { workspace = true }
tetra-config = { workspace = true }
tetra-saps = { workspace = true }
tetra-pdus = { workspace = true }
as-any = { workspace = true }
num = { workspace = true }
num-complex = { workspace = true }
rustfft = { workspace = true }
soapysdr = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
crossbeam-channel = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bitcode = { workspace = true }
rustls = { workspace = true }
rustls-native-certs = { workspace = true }
tokio = { workspace = true }
tungstenite = { workspace = true }
httparse = { workspace = true }
uuid = { workspace = true }
md5 = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }

# Optional external crates depending on selected features
quinn = { workspace = true, optional = true }

[features]
default = ["net-transport-websocket"]

# Transport types for networked components
net-transport-quic = ["dep:quinn"]  # Unmaintained
net-transport-tcp = []              # Unmaintained
net-transport-websocket = []
