[package]
name = "bluestation-control"
version.workspace = true
edition.workspace = true

[[bin]]
name = "bluestation-control-service"
path = "src/main.rs"

[dependencies]
tetra-core = { workspace = true }
tetra-entities = { workspace = true }

crossbeam-channel = { workspace = true }
clap = { workspace = true }
tungstenite = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
base64 = { workspace = true }
argon2 = { workspace = true }
rand_core = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
